services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Kolkata
      - TZ=Asia/Kolkata
      - N8N_HOST=n8n.kaushikshahare.com
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.kaushikshahare.com
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./latex:/latex
      - ./data:/data
      - ./metadata:/metadata
      - ./scripts:/scripts

  latex:
    image: texlive/texlive
    container_name: latex
    command: >
      bash -c "apt-get update && apt-get install -y python3 python3-pip python3-venv && python3 -m venv /opt/venv && /opt/venv/bin/pip install flask && /opt/venv/bin/python3 /scripts/latex_server.py"
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    volumes:
      - ./scripts:/scripts
      - ./latex:/data
